os: linux
language: node_js
node_js: 12
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  on:
    branch: master
  provider: pages
  token: $GITHUB_DEPLOY_TOKEN
  local_dir: dist
  skip_cleanup: true
cache:
  npm: true
  directories:
    - .linaria-cache
    - .sticker-pack-cache
