name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Configure ssh-agent to use our Deploy Key.
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}

      # Try to load a cached version of our node_modules folder based on the
      # hash of our lockfile.
      - name: Use Dependencies Cache
        id: dependencies-cache
        uses: actions/cache@v1
        with:
          key: dependencies-${{ hashFiles('package-lock.json') }}
          path: node_modules

      # Try to load a cached version of our .sticker-pack-cache based on the
      # hash of stickers.yml.
      - name: Use Sticker Pack Cache
        id: sticker-pack-cache
        uses: actions/cache@v1
        with:
          key: sticker-packs-${{ hashFiles('stickers.yml') }}
          path: node_modules

      # If no cache was found, install dependencies manually.
      - name: Install Dependencies
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        run: npm ci

      # Build the project.
      - name: Build Project
        run: npx nps build

      # Deploy the contents of our dist folder to the gh-pages branch.
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: dist
          SINGLE_COMMIT: true
